site_name: The Minimal Programming Language
repo_url: https://github.com/JuniorBecari10/minimal/
copyright: Copyright &copy; 2025 Antônio Carlos (JuniorBecari10)

theme:
    name: material
    color_mode: auto
    language: en

    favicon: img/logo.png
    logo: img/logo.png

    palette:
      - scheme: default
        primary: indigo
        accent: indigo
        
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      
      - scheme: slate
        primary: indigo
        accent: indigo
        
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

    code:
      highlight_theme: github-dark
    
    features:
      - navigation.footer
      - navigation.tabs
      - navigation.sections
      - navigation.indexes
      - navigation.path
      - navigation.top

      - palette.toggle
      - palette.auto

nav:
  - Home: index.md

  - Reference Book:
      - Overview: reference/overview.md
      - How to Use: reference/how-to-use.md

      - "1. Getting Started":
          - "1. Getting Started": reference/1-getting-started/index.md
          - "1.1 - Installation": reference/1-getting-started/1.1-installation.md
          - "1.2 - Hello, World!": reference/1-getting-started/1.2-hello-world.md

      - "2. The Basics":
        - "2. The Basics": reference/2-the-basics/index.md
        - "2.1 - Variables": reference/2-the-basics/2.1-variables.md
        - "2.2 - Types": reference/2-the-basics/2.2-types.md

  - Technical Book:
      - Overview: technical/overview.md
